[package]
name = "forklift"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
serde = { version = "*", features = ["derive"] }
tokio = { version = "1.43.0", features = [
  "full",
  # "rt",
  # "io-util",
  # "time",
  # "macros",
  # "sync",
] }
